package com.example.cards_2

object Database{
    val figures = mutableListOf(mutableListOf(R.drawable.grey1, R.drawable.grey2, R.drawable.grey3,R.drawable.grey4,R.drawable.grey5,R.drawable.grey6,R.drawable.grey7,R.drawable.grey8,R.drawable.grey9,R.drawable.grey10,R.drawable.grey11,R.drawable.grey12),mutableListOf(R.drawable.pink1, R.drawable.pink2, R.drawable.pink3,R.drawable.pink4,R.drawable.pink5,R.drawable.pink6,R.drawable.pink7,R.drawable.pink8,R.drawable.pink9,R.drawable.pink10,R.drawable.pink11,R.drawable.pink12),mutableListOf(R.drawable.blue1, R.drawable.blue2, R.drawable.blue3,R.drawable.blue4,R.drawable.blue5,R.drawable.blue6,R.drawable.blue7,R.drawable.blue8,R.drawable.blue9,R.drawable.blue10,R.drawable.blue11,R.drawable.blue12),mutableListOf(R.drawable.green1, R.drawable.green2, R.drawable.green3,R.drawable.green4,R.drawable.green5,R.drawable.green6,R.drawable.green7,R.drawable.green8,R.drawable.green9,R.drawable.green10,R.drawable.green11,R.drawable.green12),mutableListOf(R.drawable.yellow1, R.drawable.yellow2, R.drawable.yellow3,R.drawable.yellow4,R.drawable.yellow5,R.drawable.yellow6,R.drawable.yellow7,R.drawable.yellow8,R.drawable.yellow9,R.drawable.yellow10,R.drawable.yellow11,R.drawable.yellow12),mutableListOf(R.drawable.purple1, R.drawable.purple2, R.drawable.purple3,R.drawable.purple4,R.drawable.purple5,R.drawable.purple6,R.drawable.purple7,R.drawable.purple8,R.drawable.purple9,R.drawable.purple10,R.drawable.purple11,R.drawable.purple12))
    val figures_dark = mutableListOf(mutableListOf(R.drawable.grey1, R.drawable.grey2, R.drawable.grey3,R.drawable.grey4,R.drawable.grey5,R.drawable.grey6,R.drawable.grey7,R.drawable.grey8,R.drawable.grey9,R.drawable.grey10,R.drawable.grey11,R.drawable.grey12),mutableListOf(R.drawable.pink1, R.drawable.pink2, R.drawable.pink3,R.drawable.pink4,R.drawable.pink5,R.drawable.pink6,R.drawable.pink7,R.drawable.pink8,R.drawable.pink9,R.drawable.pink10,R.drawable.pink11,R.drawable.pink12),mutableListOf(R.drawable.blue1, R.drawable.blue2, R.drawable.blue3,R.drawable.blue4,R.drawable.blue5,R.drawable.blue6,R.drawable.blue7,R.drawable.blue8,R.drawable.blue9,R.drawable.blue10,R.drawable.blue11,R.drawable.blue12),mutableListOf(R.drawable.green1, R.drawable.green2, R.drawable.green3,R.drawable.green4,R.drawable.green5,R.drawable.green6,R.drawable.green7,R.drawable.green8,R.drawable.green9,R.drawable.green10,R.drawable.green11,R.drawable.green12),mutableListOf(R.drawable.yellow1, R.drawable.yellow2, R.drawable.yellow3,R.drawable.yellow4,R.drawable.yellow5,R.drawable.yellow6,R.drawable.yellow7,R.drawable.yellow8,R.drawable.yellow9,R.drawable.yellow10,R.drawable.yellow11,R.drawable.yellow12),mutableListOf(R.drawable.purple1, R.drawable.purple2, R.drawable.purple3,R.drawable.purple4,R.drawable.purple5,R.drawable.purple6,R.drawable.purple7,R.drawable.purple8,R.drawable.purple9,R.drawable.purple10,R.drawable.purple11,R.drawable.purple12))
    val vowel = mutableListOf(mutableListOf("У", "Ы", "И", "Э", "О", "А"), mutableListOf("Ы", "И", "Э", "О", "А", "У"),mutableListOf("И", "Э", "О", "А","У", "Ы"),mutableListOf("Э", "О", "А","У", "Ы", "И"),mutableListOf("О", "А","У", "Ы", "И", "Э"))
    val consonant = mutableListOf<String>("М","Н","Л","Й","С","П","Т","Р","К","Ч","Ш","Х")
    val hour_vowel = mutableListOf("А", "У", "Ы", "И", "Э", "О")
    val role = mutableListOf<String>("командир","алхимик","агрессор","хозяйка","красавица","игрок","купец","силач","гонщик","артист","сочинитель","мудрец")
//    val month_word = mutableListOf<String>("управление","исследование","нападение","порядок","очарование","азарт","расчёт","мощь","скорость","маскировка","творчество","знание")
    val vowel_word = mutableListOf(mutableListOf("сражение", "трапеза", "обучение", "танцы", "созерцание", "пение"), mutableListOf("трапеза", "обучение", "танцы", "созерцание", "пение","сражение"),mutableListOf("обучение", "танцы", "созерцание", "пение","сражение", "трапеза"),mutableListOf("танцы", "созерцание", "пение","сражение", "трапеза", "обучение"),mutableListOf("созерцание", "пение","сражение", "трапеза", "обучение", "танцы"))

//    val month_day_words = mutableListOf(mutableListOf<String>("- встреча", "- знакомство", "- развитие","- результат","- расставание"), mutableListOf<String>("находит глину ", "делает чашу ", "наполняет чашу ","выпивает нектар ","разбивает чашу "))
    val heroes = mutableListOf(mutableListOf("луна", "орёл", "трава","лосось","медведь","ящерица"), mutableListOf("солнце", "воробей", "ягода","ракушка","кабарга","змея"), mutableListOf("комета", "ворона", "бамбук","акула","росомаха","крыса"), mutableListOf("звезда", "пчела", "ива","нерпа","белка","муравей"), mutableListOf("молния", "стрекоза", "ель","навага","соболь","лягушка"), mutableListOf("ветер", "бабочка", "сосна","тюлень","лошадь","червяк"), mutableListOf("дождь", "муха", "рябина","краб","олень","жук"), mutableListOf("лед", "комар", "дуб","кит","рысь","жаба"), mutableListOf("снег", "чайка", "береза","таймень","заяц","мышка"), mutableListOf("туман", "утка", "папоротник","камбала","лиса","ёжик"), mutableListOf("облако", "журавль", "гриб","медуза","горностай","улитка"), mutableListOf("радуга", "филин", "мох","осьминог","собака","паук"))
    val heroes2 = mutableListOf(mutableListOf("c луной", "с орлом", "с травой","с лососем","с медведем","с ящерицей"), mutableListOf("с солнцем", "с воробьём", "с ягодой","с ракушкой","с кабаргой","со змеёй"), mutableListOf("с кометой", "с вороной", "с бамбуком","с акулой","с росомахой","с крысой"), mutableListOf("со звездой", "с пчелой", "с ивой","с нерпой","с белкой","с муравьём"), mutableListOf("с молнией", "сл стрекозой", "с елью","с навагой","с соболем","с лягушкой"), mutableListOf("с ветром", "с бабочкой", "с сосной","с тюленем","с лошадью","с червяком"), mutableListOf("с дождём", "с мухой", "с рябиной","с крабом","с оленем","с жуком"), mutableListOf("со льдом", "с комаром", "с дубом","с китом","с рысью","с жабой"), mutableListOf("со снегом", "с чайкой", "с березой","с тайменем","с зайцем","с мышкой"), mutableListOf("с туманом", "с уткой", "с папоротником","с камбалой","с лисой","с ёжиком"), mutableListOf("с облаком", "с журавлём", "с грибом","с медузой","с горностаем","с улиткой"), mutableListOf("с радугой", "с филином", "с мхом","с осьминогом","с собакой","с пауком"))
    val heroes3 = mutableListOf(mutableListOf("луну", "орла", "траву","лосося","медведя","ящерицу"), mutableListOf("солнце", "воробья", "ягоду","ракушку","кабаргу","змею"), mutableListOf("комету", "ворону", "бамбук","акулу","росомаху","крысу"), mutableListOf("звезду", "пчелу", "иву","нерпу","белку","муравья"), mutableListOf("молнию", "стрекозу", "ель","навагу","соболя","лягушку"), mutableListOf("ветер", "бабочку", "сосну","тюленю","лошадь","червяка"), mutableListOf("дождь", "муху", "рябину","краба","оленя","жука"), mutableListOf("лед", "комара", "дуб","кита","рысь","жабу"), mutableListOf("снег", "чайку", "березу","тайменя","зайца","мышку"), mutableListOf("туман", "утку", "папоротник","камбалу","лису","ёжика"), mutableListOf("облако", "журавля", "гриб","медузу","горностая","улитку"), mutableListOf("радугу", "филина", "мох","осьминога","собаку","паука"))
    val heroes_with_end1 = mutableListOf(mutableListOf("ая луна", "ой орёл", "ая трава","ой лосось","ой медведь","ая ящерица"), mutableListOf("ое солнце", "ой воробей", "ая ягода","ая ракушка","ая кабарга","ая змея"), mutableListOf("ая комета", "ая ворона", "ой бамбук","ая акула","ая росомаха","ая крыса"), mutableListOf("ая звезда", "ая пчела", "ая ива","ая нерпа","ая белка","ой муравей"), mutableListOf("ая молния", "ая стрекоза", "ая ель","ая навага","ой соболь","ая лягушка"), mutableListOf("ой ветер", "ая бабочка", "ая сосна","ой тюлень","ая лошадь","ой червяк"), mutableListOf("ой дождь", "ая муха", "ая рябина","ой краб","ой олень","ой жук"), mutableListOf("ой лед", "ой комар", "ой дуб","ой кит","ая рысь","ая жаба"), mutableListOf("ой снег", "ая чайка", "ая береза","ой таймень","ой заяц","ая мышка"), mutableListOf("ой туман", "ая утка", "ой папоротник","ая камбала","ая лиса","ой ёжик"), mutableListOf("ое облако", "ой журавль", "ой гриб","ая медуза","ой горностай","ая улитка"), mutableListOf("ая радуга", "ой филин", "ой мох","ой осьминог","ая собака","ой паук"))
    val heroes_with_end2 = mutableListOf(mutableListOf("ая луна", "ый орёл", "ая трава","ый лосось","ый медведь","ая ящерица"), mutableListOf("ое солнце", "ый воробей", "ая ягода","ая ракушка","ая кабарга","ая змея"), mutableListOf("ая комета", "ая ворона", "ый бамбук","ая акула","ая росомаха","ая крыса"), mutableListOf("ая звезда", "ая пчела", "ая ива","ая нерпа","ая белка","ый муравей"), mutableListOf("ая молния", "ая стрекоза", "ая ель","ая навага","ый соболь","ая лягушка"), mutableListOf("ый ветер", "ая бабочка", "ая сосна","ый тюлень","ая лошадь","ый червяк"), mutableListOf("ый дождь", "ая муха", "ая рябина","ый краб","ый олень","ый жук"), mutableListOf("ый лед", "ый комар", "ый дуб","ый кит","ая рысь","ая жаба"), mutableListOf("ый снег", "ая чайка", "ая береза","ый таймень","ый заяц","ая мышка"), mutableListOf("ый туман", "ая утка", "ый папоротник","ая камбала","ая лиса","ый ёжик"), mutableListOf("ое облако", "ый журавль", "ый гриб","ая медуза","ый горностай","ая улитка"), mutableListOf("ая радуга", "ый филин", "ый мох","ый осьминог","ая собака","ый паук"))
    val role2 = mutableListOf<String>("командиру","алхимику","агрессору","хозяйке","красавице","игроку","купцу","силачу","гонщику","артисту","сочинителю","мудрецу")
    val role3 = mutableListOf<String>("командиром","алхимиком","агрессором","хозяйкой","красавицей","игроком","купцом","силачом","гонщиком","артистом","сочинителем","мудрецом")
    val verb = mutableListOf(mutableListOf("находит глину"," - встреча"), mutableListOf("делает чашу"," - знакомство"), mutableListOf("наполняет чашу"," - развитие"), mutableListOf("выпивает нектар"," - результат"), mutableListOf("разбивает чашу"," - расставание"))
    val second_text = mutableListOf(mutableListOf("Сражение в пещере самочувствия.","Трапеза на дороге добычи.","Обучение в водоёме отношений.","Танцы в лесу премудрости.","Созерцание в небе впечатлений.", "Пение в космосе бесконечной веры."),mutableListOf("Трапеза в пещере самочувствия.","Обучение на дороге добычи.","Танцы в водоёме отношений.","Созерцание в лесу премудрости.","Пение в небе впечатлений.", "Сражение в космосе бесконечной веры."),mutableListOf("Обучение в в пещере самочувствия.","Танцы на дороге добычи.","Созерцание в водоёме отношений.","Пение в лесу премудрости.","Сражение в небе впечатлений.", "Трапеза в космосе бесконечной веры."),mutableListOf("Танцы в пещере самочувствия.","Созерцание на дороге добычи.","Пение в водоёме отношений.","Сражение в лесу премудрости.","Трапеза в небе впечатлений.", "Обучение в космосе бесконечной веры."),mutableListOf("Созерцание в пещере самочувствия.","Пение на дороге добычи.","Сражение в водоёме отношений.","Трапеза в лесу премудрости.","Обучение в небе впечатлений.", "Танцы в космосе бесконечной веры."))
    val emotions = mutableListOf(" - радость.", " - спокойствие.", " - раздражение.", " - испуг.", " - удивление.")
    val verb3 = mutableListOf(mutableListOf("созерцает","поёт","сражается","трапезничает","учит", "танцует"), mutableListOf("сражается","трапезничает","учит","танцует","созерцает"), mutableListOf("трапезничает","учит","танцует","созерцает","поёт", "сражается"), mutableListOf("учит","танцует","созерцает","поёт","сражается", "трапезничает"), mutableListOf("танцует","созерцает","поёт","сражается","трапезничает", "учит"))
    val properties = mutableListOf("ое упраление","ое изучение","ое нападение","ый порядок","ое очарование","ый риск","ый расчет","ое усиление","ое ускорение","ая маскировка","ое творчество","ое понимание")
    val intentions = mutableListOf("командовать","исследовать","нападать","наводить порядок","очаровывать","рисковать","рассчитывать","усиливаться","ускоряться","прятаться","придумывать","понимать")
    val cards = mutableListOf(
        mutableListOf(0, 2, mutableListOf("ума", "ой ум", "уму", "ум"), mutableListOf("ю корону", "короны", "е короны"),"сияют","тускнеют", "разрубают", "защищают"),
        mutableListOf(0,1,mutableListOf("ума", "ой ум", "уму", "ум"), mutableListOf("ю корону", "короны", "е короны"),"сияют","тускнеют", "вращается","останавливается"),
        mutableListOf(1,0, mutableListOf("чувства", "ое чувство", "чувству", "чувство"), mutableListOf("ё кольцо", "кольца", "а кольца"),"вращаются","останавливаются","сияют","тускнеют"),
        mutableListOf(1,3,mutableListOf("чувства", "ое чувство", "чувству", "чувство"), mutableListOf("ё кольцо", "кольца", "а кольца"),"вращаются","останавливаются","звенят", "замолкают"),
        mutableListOf(1,2,mutableListOf("чувства", "ое чувство", "чувству", "чувство"), mutableListOf("ё кольцо", "кольца", "а кольца"),"вращаются","останавливаются","разрубают", "защищают"),
        mutableListOf(2,1, mutableListOf("силы", "ая сила", "силе", "силу"), mutableListOf("й меч", "мечи", "а меча"),"разрубают","защищают","вращаются","останавливаются"),
        mutableListOf(2,0,mutableListOf("силы", "ая сила", "силе", "силу"), mutableListOf("й меч", "мечи", "а меча"),"разрубают","защищают","сияют","тускнеют"),
        mutableListOf(2,3,mutableListOf("силы", "ая сила", "силе", "силу"), mutableListOf("й меч", "мечи", "а меча"), "разрубают","защищают","звенят", "замолкают"),
        mutableListOf(3,2, mutableListOf("фантазии", "ая фантазия", "фантазии", "фантазию"), mutableListOf("й колокольчик, колокольчики, а колокольчика"), "звенят", "замолкают","разрубают", "защищают"),
        mutableListOf(3,1,mutableListOf("фантазии", "ая фантазия", "фантазии", "фантазию"), mutableListOf("й колокольчик, колокольчики, а колокольчика"), "звенят", "замолкают","вращаются","останавливаются"),
        mutableListOf(3,0,mutableListOf("фантазии", "ая фантазия", "фантазии", "фантазию"), mutableListOf("й колокольчик, колокольчики, а колокольчика"), "звенят", "замолкают","сияют","тускнеют"),
        mutableListOf(0,3,mutableListOf("ума", "ой ум", "уму", "ум"), mutableListOf("ю корону", "короны", "е короны"),"сияют","тускнеют","звенят", "замолкают"))
//    val prop_pad = mutableListOf<MutableList<String>>(mutableListOf<String>("ума", "ой ум", "уму", "ум"),mutableListOf<String>("ума", "ой ум", "уму", "ум"),mutableListOf<String>("чувства", "ое чувство", "чувству", "чувство"),mutableListOf<String>("чувства", "ое чувство", "чувству", "чувство"), mutableListOf<String>("чувства", "ое чувство", "чувству", "чувство"), mutableListOf<String>("силы", "ая сила", "силе", "силу"), mutableListOf<String>("силы", "ая сила", "силе", "силу"), mutableListOf<String>("силы", "ая сила", "силе", "силу"), mutableListOf<String>("фантазии", "ая фантазия", "фантазии", "фантазию"),mutableListOf<String>("фантазии", "ая фантазия", "фантазии", "фантазию"),mutableListOf<String>("фантазии", "ая фантазия", "фантазии", "фантазию"),mutableListOf<String>("ума", "ой ум", "уму", "ум"))
//    val attr_pad = mutableListOf<MutableList<String>>(mutableListOf("ю корону", "короны", "е короны"),mutableListOf("ю корону", "короны", "е короны"), mutableListOf("ё кольцо", "кольца", "а кольца"), mutableListOf("ё кольцо", "кольца", "а кольца"), mutableListOf("ё кольцо", "кольца", "а кольца"), mutableListOf("й меч", "мечи", "а меча"), mutableListOf("й меч", "мечи", "а меча"),mutableListOf("й меч", "мечи", "а меча"),mutableListOf("й колокольчик", "колокольчики", "а колокольчика"),mutableListOf("й колокольчик", "колокольчики", "а колокольчика"),mutableListOf("й колокольчик", "колокольчики", "а колокольчика"), mutableListOf("ю корону", "короны", "е короны"))

    val prop_pad = mutableListOf(mutableListOf<String>("ума", "ой ум", "уму", "ум"), mutableListOf<String>("чувства", "ое чувство", "чувству", "чувство"), mutableListOf<String>("силы", "ая сила", "силе", "силу"), mutableListOf<String>("фантазии", "ая фантазия", "фантазии", "фантазию"))
    val attr_pad = mutableListOf(mutableListOf("ю корону", "короны", "е короны", "корону"), mutableListOf("ё кольцо", "кольца", "а кольца", "кольцо"),mutableListOf("й меч", "мечи", "а меча", "меч"),mutableListOf("й колокольчик", "колокольчики", "а колокольчика", "колокольчик"))
}
